services:
  tex:
    build: .
    image: custom-tex-image
    volumes:
      - .:/ws
    # will use `git` on /ws, so do not mount ./project
    working_dir: /ws/project
    command:
      - "bash"
      - "build.sh"
